version: 2.1

jobs:
  abc:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py
  def:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py
  djkl:
    docker:
      - image: cimg/python:3.11
    steps:
      - run: echo "Deploying to production server"

workflows:
  abc_and_def_djkl:
    jobs:
      - abc
      - test:
          requires:
            - abc 
      - djkl:
          requires:
            - def
          filters:
            branches:
              only: main